package search

var abbreviations = map[string]string{
	"ge":      "Genesis",
	"gn":      "Genesis",
	"gen":     "Genesis",
	"gene":    "Genesis",
	"genesis": "Genesis",

	"ex":     "Exodus",
	"exo":    "Exodus",
	"exod":   "Exodus",
	"exodus": "Exodus",

	"leviticus": "Leviticus",
	"lev":       "Leviticus",
	"le":        "Leviticus",
	"lv":        "Leviticus",

	"numbers": "Numbers",
	"num":     "Numbers",
	"nu":      "Numbers",
	"nm":      "Numbers",
	"nb":      "Numbers",

	"deuteronomy": "Deuteronomy",
	"deut":        "Deuteronomy",
	"de":          "Deuteronomy",
	"dt":          "Deuteronomy",

	"joshua": "Joshua",
	"josh":   "Joshua",
	"jos":    "Joshua",
	"jsh":    "Joshua",

	"judges": "Judges",
	"judg":   "Judges",
	"jdg":    "Judges",
	"jg":     "Judges",
	"jdgs":   "Judges",

	"ruth": "Ruth",
	"rth":  "Ruth",
	"ru":   "Ruth",

	"1samuel":     "1 Samuel",
	"1sam":        "1 Samuel",
	"1sm":         "1 Samuel",
	"1sa":         "1 Samuel",
	"1s":          "1 Samuel",
	"isam":        "1 Samuel",
	"1stsamuel":   "1 Samuel",
	"1stsam":      "1 Samuel",
	"firstsamuel": "1 Samuel",
	"firstsam":    "1 Samuel",

	"2samuel":      "2 Samuel",
	"2sam":         "2 Samuel",
	"2sm":          "2 Samuel",
	"2sa":          "2 Samuel",
	"2s":           "2 Samuel",
	"iisam":        "2 Samuel",
	"2ndsamuel":    "2 Samuel",
	"2ndsam":       "2 Samuel",
	"secondsamuel": "2 Samuel",
	"secondsam":    "2 Samuel",

	"1kings":     "1 Kings",
	"1kgs":       "1 Kings",
	"1ki":        "1 Kings",
	"1kin":       "1 Kings",
	"1k":         "1 Kings",
	"ikgs":       "1 Kings",
	"iki":        "1 Kings",
	"1stkings":   "1 Kings",
	"1stkgs":     "1 Kings",
	"firstkings": "1 Kings",
	"firstkgs":   "1 Kings",

	"2kings":      "2 Kings",
	"2kgs":        "2 Kings",
	"2ki":         "2 Kings",
	"2kin":        "2 Kings",
	"2k":          "2 Kings",
	"iikgs":       "2 Kings",
	"iiki":        "2 Kings",
	"2ndkings":    "2 Kings",
	"2ndkgs":      "2 Kings",
	"secondkings": "2 Kings",
	"secondkgs":   "2 Kings",

	"1chronicles":     "1 Chronicles",
	"1chron":          "1 Chronicles",
	"1chr":            "1 Chronicles",
	"1ch":             "1 Chronicles",
	"ichron":          "1 Chronicles",
	"ichr":            "1 Chronicles",
	"ich":             "1 Chronicles",
	"1stchronicles":   "1 Chronicles",
	"1stchron":        "1 Chronicles",
	"firstchronicles": "1 Chronicles",
	"firstchron":      "1 Chronicles",

	"2chronicles":      "2 Chronicles",
	"2chron":           "2 Chronicles",
	"2chr":             "2 Chronicles",
	"2ch":              "2 Chronicles",
	"iichron":          "2 Chronicles",
	"iichr":            "2 Chronicles",
	"iich":             "2 Chronicles",
	"2ndchronicles":    "2 Chronicles",
	"2ndchron":         "2 Chronicles",
	"secondchronicles": "2 Chronicles",
	"secondchron":      "2 Chronicles",

	"ezra": "Ezra",
	"ezr":  "Ezra",
	"ez":   "Ezra",

	"nehemiah": "Nehemiah",
	"neh":      "Nehemiah",
	"ne":       "Nehemiah",

	"esther": "Esther",
	"est":    "Esther",
	"esth":   "Esther",
	"es":     "Esther",

	"job": "Job",
	"jb":  "Job",

	"psalms": "Psalms",
	"ps":     "Psalms",
	"psalm":  "Psalms",
	"pslm":   "Psalms",
	"psa":    "Psalms",
	"psm":    "Psalms",
	"pss":    "Psalms",

	"proverbs": "Proverbs",
	"prov":     "Proverbs",
	"pro":      "Proverbs",
	"prv":      "Proverbs",
	"pr":       "Proverbs",

	"ecclesiastes": "Ecclesiastes",
	"eccles":       "Ecclesiastes",
	"eccle":        "Ecclesiastes",
	"ecc":          "Ecclesiastes",
	"ec":           "Ecclesiastes",
	"qoh":          "Ecclesiastes",

	"songofsolomon":       "Song of Solomon",
	"song":                "Song of Solomon",
	"songofsongs":         "Song of Solomon",
	"sos":                 "Song of Solomon",
	"so":                  "Song of Solomon",
	"canticleofcanticles": "Song of Solomon",
	"canticles":           "Song of Solomon",
	"cant":                "Song of Solomon",

	"isaiah": "Isaiah",
	"isa":    "Isaiah",
	"is":     "Isaiah",

	"jeremiah": "Jeremiah",
	"jer":      "Jeremiah",
	"je":       "Jeremiah",
	"jr":       "Jeremiah",

	"lamentations": "Lamentations",
	"lam":          "Lamentations",
	"la":           "Lamentations",

	"ezekiel": "Ezekiel",
	"ezek":    "Ezekiel",
	"eze":     "Ezekiel",
	"ezk":     "Ezekiel",

	"daniel": "Daniel",
	"dan":    "Daniel",
	"da":     "Daniel",
	"dn":     "Daniel",

	"hosea": "Hosea",
	"hos":   "Hosea",
	"ho":    "Hosea",

	"joel": "Joel",
	"jl":   "Joel",

	"amos": "Amos",
	"am":   "Amos",

	"obadiah": "Obadiah",
	"obad":    "Obadiah",
	"ob":      "Obadiah",

	"jonah": "Jonah",
	"jnh":   "Jonah",
	"jon":   "Jonah",

	"micah": "Micah",
	"mic":   "Micah",
	"mc":    "Micah",

	"nahum": "Nahum",
	"nah":   "Nahum",
	"na":    "Nahum",

	"habakkuk": "Habakkuk",
	"hab":      "Habakkuk",
	"hb":       "Habakkuk",

	"zephaniah": "Zephaniah",
	"zeph":      "Zephaniah",
	"zep":       "Zephaniah",
	"zp":        "Zephaniah",

	"haggai": "Haggai",
	"hag":    "Haggai",
	"hg":     "Haggai",

	"zechariah": "Zechariah",
	"zech":      "Zechariah",
	"zec":       "Zechariah",
	"zc":        "Zechariah",

	"malachi": "Malachi",
	"mal":     "Malachi",
	"ml":      "Malachi",

	"matthew": "Matthew",
	"matt":    "Matthew",
	"mt":      "Matthew",

	"mark": "Mark",
	"mrk":  "Mark",
	"mar":  "Mark",
	"mk":   "Mark",
	"mr":   "Mark",

	"luke": "Luke",
	"luk":  "Luke",
	"lk":   "Luke",

	"john": "John",
	"joh":  "John",
	"jhn":  "John",
	"jn":   "John",

	"acts": "Acts",
	"act":  "Acts",
	"ac":   "Acts",

	"romans": "Romans",
	"rom":    "Romans",
	"ro":     "Romans",
	"rm":     "Romans",

	"1corinthians":     "1 Corinthians",
	"1cor":             "1 Corinthians",
	"1co":              "1 Corinthians",
	"icor":             "1 Corinthians",
	"ico":              "1 Corinthians",
	"icorinthians":     "1 Corinthians",
	"1stcorinthians":   "1 Corinthians",
	"firstcorinthians": "1 Corinthians",

	"2corinthians":      "2 Corinthians",
	"2cor":              "2 Corinthians",
	"2co":               "2 Corinthians",
	"iicor":             "2 Corinthians",
	"iico":              "2 Corinthians",
	"iicorinthians":     "2 Corinthians",
	"2ndcorinthians":    "2 Corinthians",
	"secondcorinthians": "2 Corinthians",

	"galatians": "Galatians",
	"gal":       "Galatians",
	"ga":        "Galatians",

	"ephesians": "Ephesians",
	"eph":       "Ephesians",
	"ephes":     "Ephesians",

	"philippians": "Philippians",
	"phil":        "Philippians",
	"php":         "Philippians",
	"pp":          "Philippians",

	"colossians": "Colossians",
	"col":        "Colossians",
	"co":         "Colossians",

	"1thessalonians":     "1 Thessalonians",
	"1thess":             "1 Thessalonians",
	"1thes":              "1 Thessalonians",
	"1th":                "1 Thessalonians",
	"ithessalonians":     "1 Thessalonians",
	"ithess":             "1 Thessalonians",
	"ithes":              "1 Thessalonians",
	"ith":                "1 Thessalonians",
	"1stthessalonians":   "1 Thessalonians",
	"1stthess":           "1 Thessalonians",
	"firstthessalonians": "1 Thessalonians",
	"firstthess":         "1 Thessalonians",

	"2thessalonians":      "2 Thessalonians",
	"2thess":              "2 Thessalonians",
	"2thes":               "2 Thessalonians",
	"2th":                 "2 Thessalonians",
	"iithessalonians":     "2 Thessalonians",
	"iithess":             "2 Thessalonians",
	"iithes":              "2 Thessalonians",
	"iith":                "2 Thessalonians",
	"2ndthessalonians":    "2 Thessalonians",
	"2ndthess":            "2 Thessalonians",
	"secondthessalonians": "2 Thessalonians",
	"secondthess":         "2 Thessalonians",

	"1timothy":     "1 Timothy",
	"1tim":         "1 Timothy",
	"1ti":          "1 Timothy",
	"itimothy":     "1 Timothy",
	"itim":         "1 Timothy",
	"iti":          "1 Timothy",
	"1sttimothy":   "1 Timothy",
	"1sttim":       "1 Timothy",
	"firsttimothy": "1 Timothy",
	"firsttim":     "1 Timothy",

	"2timothy":      "2 Timothy",
	"2tim":          "2 Timothy",
	"2ti":           "2 Timothy",
	"iitimothy":     "2 Timothy",
	"iitim":         "2 Timothy",
	"iiti":          "2 Timothy",
	"2ndtimothy":    "2 Timothy",
	"2ndtim":        "2 Timothy",
	"secondtimothy": "2 Timothy",
	"secondtim":     "2 Timothy",

	"titus": "Titus",
	"tit":   "Titus",
	"ti":    "Titus",

	"philemon": "Philemon",
	"philem":   "Philemon",
	"phm":      "Philemon",
	"pm":       "Philemon",

	"hebrews": "Hebrews",
	"heb":     "Hebrews",

	"james": "James",
	"jas":   "James",
	"jm":    "James",

	"1peter":     "1 Peter",
	"1pet":       "1 Peter",
	"1pe":        "1 Peter",
	"1pt":        "1 Peter",
	"1p":         "1 Peter",
	"ipet":       "1 Peter",
	"ipt":        "1 Peter",
	"ipe":        "1 Peter",
	"ipeter":     "1 Peter",
	"1stpeter":   "1 Peter",
	"firstpeter": "1 Peter",

	"2peter":      "2 Peter",
	"2pet":        "2 Peter",
	"2pe":         "2 Peter",
	"2pt":         "2 Peter",
	"2p":          "2 Peter",
	"iipeter":     "2 Peter",
	"iipet":       "2 Peter",
	"iipt":        "2 Peter",
	"iipe":        "2 Peter",
	"2ndpeter":    "2 Peter",
	"secondpeter": "2 Peter",

	"1john":     "1 John",
	"1jhn":      "1 John",
	"1jn":       "1 John",
	"1j":        "1 John",
	"1joh":      "1 John",
	"1jo":       "1 John",
	"ijohn":     "1 John",
	"ijhn":      "1 John",
	"ijoh":      "1 John",
	"ijn":       "1 John",
	"ijo":       "1 John",
	"1stjohn":   "1 John",
	"firstjohn": "1 John",

	"2john":      "2 John",
	"2jhn":       "2 John",
	"2jn":        "2 John",
	"2j":         "2 John",
	"2joh":       "2 John",
	"2jo":        "2 John",
	"iijohn":     "2 John",
	"iijhn":      "2 John",
	"iijoh":      "2 John",
	"iijn":       "2 John",
	"iijo":       "2 John",
	"2ndjohn":    "2 John",
	"secondjohn": "2 John",

	"3john":     "3 John",
	"3jhn":      "3 John",
	"3jn":       "3 John",
	"3j":        "3 John",
	"3joh":      "3 John",
	"3jo":       "3 John",
	"iiijohn":   "3 John",
	"iiijhn":    "3 John",
	"iiijoh":    "3 John",
	"iiijn":     "3 John",
	"iiijo":     "3 John",
	"3rdjohn":   "3 John",
	"thirdjohn": "3 John",

	"jude": "Jude",
	"jud":  "Jude",
	"jd":   "Jude",

	"revelation":    "Revelation",
	"rev":           "Revelation",
	"re":            "Revelation",
	"therevelation": "Revelation",
}
