package search

type reference struct {
	match string
	book  string
}

var references = []reference{
	{"ge", "Genesis"},
	{"gn", "Genesis"},
	{"gen", "Genesis"},
	{"gene", "Genesis"},
	{"genesis", "Genesis"},

	{"ex", "Exodus"},
	{"exo", "Exodus"},
	{"exod", "Exodus"},
	{"exodus", "Exodus"},

	{"leviticus", "Leviticus"},
	{"lev", "Leviticus"},
	{"le", "Leviticus"},
	{"lv", "Leviticus"},

	{"numbers", "Numbers"},
	{"num", ""},
	{"nu", ""},
	{"nm", ""},
	{"nb", ""},

	{"deuteronomy", ""},
	{"deut", ""},
	{"de", ""},
	{"dt", ""},

	{"joshua", ""},
	{"josh", ""},
	{"jos", ""},
	{"jsh", ""},

	{"judges", ""},
	{"judg", ""},
	{"jdg", ""},
	{"jg", ""},
	{"jdgs", ""},

	{"ruth", ""},
	{"ruth", ""},
	{"rth", ""},
	{"ru", ""},

	{"1samuel", ""},
	{"1sam", ""},
	{"1sm", ""},
	{"1sa", ""},
	{"1s", ""},
	{"isam", ""},
	{"isa", ""},
	{"1sam", ""},
	{"1sa", ""},
	{"1s", ""},
	{"1stsamuel", ""},
	{"1stsam", ""},
	{"firstsamuel", ""},
	{"firstsam", ""},

	{"2samuel", ""},
	{"2sam", ""},
	{"2sm", ""},
	{"2sa", ""},
	{"2s", ""},
	{"iisam", ""},
	{"iisa", ""},
	{"2sam", ""},
	{"2sa", ""},
	{"2s", ""},
	{"2ndsamuel", ""},
	{"2ndsam", ""},
	{"secondsamuel", ""},
	{"secondsam", ""},

	{"1kings", ""},
	{"1kings", ""},
	{"1kgs", ""},
	{"1ki", ""},
	{"1kgs", ""},
	{"1kin", ""},
	{"1ki", ""},
	{"1k", ""},
	{"ikgs", ""},
	{"iki", ""},
	{"1stkings", ""},
	{"1stkgs", ""},
	{"firstkings", ""},
	{"firstkgs", ""},

	{"2kings", ""},
	{"2kings", ""},
	{"2kgs", ""},
	{"2ki", ""},
	{"2kgs", ""},
	{"2kin", ""},
	{"2ki", ""},
	{"2k", ""},
	{"iikgs", ""},
	{"iiki", ""},
	{"2ndkings", ""},
	{"2ndkgs", ""},
	{"secondkings", ""},
	{"secondkgs", ""},

	{"1chronicles", ""},
	{"1chron", ""},
	{"1chr", ""},
	{"1ch", ""},
	{"1chron", ""},
	{"1chr", ""},
	{"1ch", ""},
	{"ichron", ""},
	{"ichr", ""},
	{"ich", ""},
	{"1stchronicles", ""},
	{"1stchron", ""},
	{"firstchronicles", ""},
	{"firstchron", ""},

	{"2chronicles", ""},
	{"2chron", ""},
	{"2chr", ""},
	{"2ch", ""},
	{"2chron", ""},
	{"2chr", ""},
	{"2ch", ""},
	{"iichron", ""},
	{"iichr", ""},
	{"iich", ""},
	{"2ndchronicles", ""},
	{"2ndchron", ""},
	{"secondchronicles", ""},
	{"secondchron", ""},

	{"ezra", ""},
	{"ezra", ""},
	{"ezr", ""},
	{"ez", ""},

	{"nehemiah", ""},
	{"neh", ""},
	{"ne", ""},

	{"esther", ""},
	{"est", ""},
	{"esth", ""},
	{"es", ""},

	{"job", ""},
	{"job", ""},
	{"jb", ""},

	{"psalms", ""},
	{"ps", ""},
	{"psalm", ""},
	{"pslm", ""},
	{"psa", ""},
	{"psm", ""},
	{"pss", ""},
	{"proverbs", ""},
	{"prov", ""},
	{"pro", ""},
	{"prv", ""},
	{"pr", ""},

	{"ecclesiastes", ""},
	{"eccles", ""},
	{"eccle", ""},
	{"ecc", ""},
	{"ec", ""},
	{"qoh", ""},

	{"songofsolomon", ""},
	{"song", ""},
	{"songofsongs", ""},
	{"sos", ""},
	{"so", ""},
	{"canticleofcanticles", ""},
	{"canticles", ""},
	{"cant", ""},

	{"isaiah", ""},
	{"isa", ""},
	{"is", ""},

	{"jeremiah", ""},
	{"jer", ""},
	{"je", ""},
	{"jr", ""},

	{"lamentations", ""},
	{"lam", ""},
	{"la", ""},

	{"ezekiel", ""},
	{"ezek", ""},
	{"eze", ""},
	{"ezk", ""},

	{"daniel", ""},
	{"dan", ""},
	{"da", ""},
	{"dn", ""},

	{"hosea", ""},
	{"hos", ""},
	{"ho", ""},

	{"joel", ""},
	{"joel", ""},
	{"jl", ""},

	{"amos", ""},
	{"amos", ""},
	{"am", ""},

	{"obadiah", ""},
	{"obad", ""},
	{"ob", ""},

	{"jonah", ""},
	{"jonah", ""},
	{"jnh", ""},
	{"jon", ""},

	{"micah", ""},
	{"mic", ""},
	{"mc", ""},

	{"nahum", ""},
	{"nah", ""},
	{"na", ""},

	{"habakkuk", ""},
	{"hab", ""},
	{"hb", ""},

	{"zephaniah", ""},
	{"zeph", ""},
	{"zep", ""},
	{"zp", ""},

	{"haggai", ""},
	{"hag", ""},
	{"hg", ""},

	{"zechariah", ""},
	{"zech", ""},
	{"zec", ""},
	{"zc", ""},

	{"malachi", ""},
	{"mal", ""},
	{"ml", ""},

	{"matthew", ""},
	{"matt", ""},
	{"mt", ""},

	{"mark", ""},
	{"mark", ""},
	{"mrk", ""},
	{"mar", ""},
	{"mk", ""},
	{"mr", ""},

	{"luke", ""},
	{"luke", ""},
	{"luk", ""},
	{"lk", ""},

	{"john", ""},
	{"john", ""},
	{"joh", ""},
	{"jhn", ""},
	{"jn", ""},

	{"acts", ""},
	{"acts", ""},
	{"act", ""},
	{"ac", ""},

	{"romans", ""},
	{"rom", ""},
	{"ro", ""},
	{"rm", ""},

	{"1corinthians", ""},
	{"1cor", ""},
	{"1co", ""},
	{"icor", ""},
	{"ico", ""},
	{"1cor", ""},
	{"1co", ""},
	{"icorinthians", ""},
	{"1corinthians", ""},
	{"1stcorinthians", ""},
	{"firstcorinthians", ""},

	{"2corinthians", ""},
	{"2cor", ""},
	{"2co", ""},
	{"iicor", ""},
	{"iico", ""},
	{"2cor", ""},
	{"2co", ""},
	{"iicorinthians", ""},
	{"2corinthians", ""},
	{"2ndcorinthians", ""},
	{"secondcorinthians", ""},

	{"galatians", ""},
	{"gal", ""},
	{"ga", ""},

	{"ephesians", ""},
	{"eph", ""},
	{"ephes", ""},

	{"philippians", ""},
	{"phil", ""},
	{"php", ""},
	{"pp", ""},

	{"colossians", ""},
	{"col", ""},
	{"co", ""},

	{"1thessalonians", ""},
	{"1thess", ""},
	{"1thes", ""},
	{"1th", ""},
	{"ithessalonians", ""},
	{"ithess", ""},
	{"ithes", ""},
	{"ith", ""},
	{"1thessalonians", ""},
	{"1thess", ""},
	{"1thes", ""},
	{"1th", ""},
	{"1stthessalonians", ""},
	{"1stthess", ""},
	{"firstthessalonians", ""},
	{"firstthess", ""},

	{"2thessalonians", ""},
	{"2thess", ""},
	{"2thes", ""},
	{"2th", ""},
	{"iithessalonians", ""},
	{"iithess", ""},
	{"iithes", ""},
	{"iith", ""},
	{"2thessalonians", ""},
	{"2thess", ""},
	{"2thes", ""},
	{"2th", ""},
	{"2ndthessalonians", ""},
	{"2ndthess", ""},
	{"secondthessalonians", ""},
	{"secondthess", ""},

	{"1timothy", ""},
	{"1tim", ""},
	{"1ti", ""},
	{"itimothy", ""},
	{"itim", ""},
	{"iti", ""},
	{"1timothy", ""},
	{"1tim", ""},
	{"1ti", ""},
	{"1sttimothy", ""},
	{"1sttim", ""},
	{"firsttimothy", ""},
	{"firsttim", ""},

	{"2timothy", ""},
	{"2tim", ""},
	{"2ti", ""},
	{"iitimothy", ""},
	{"iitim", ""},
	{"iiti", ""},
	{"2timothy", ""},
	{"2tim", ""},
	{"2ti", ""},
	{"2ndtimothy", ""},
	{"2ndtim", ""},
	{"secondtimothy", ""},
	{"secondtim", ""},

	{"titus", ""},
	{"titus", ""},
	{"tit", ""},
	{"ti", ""},

	{"philemon", ""},
	{"philem", ""},
	{"phm", ""},
	{"pm", ""},

	{"hebrews", ""},
	{"heb", ""},

	{"james", ""},
	{"james", ""},
	{"jas", ""},
	{"jm", ""},

	{"1peter", ""},
	{"1pet", ""},
	{"1pe", ""},
	{"1pt", ""},
	{"1p", ""},
	{"ipet", ""},
	{"ipt", ""},
	{"ipe", ""},
	{"1peter", ""},
	{"1pet", ""},
	{"1pe", ""},
	{"1pt", ""},
	{"1p", ""},
	{"ipeter", ""},
	{"1stpeter", ""},
	{"firstpeter", ""},

	{"2peter", ""},
	{"2pet", ""},
	{"2pe", ""},
	{"2pt", ""},
	{"2p", ""},
	{"iipeter", ""},
	{"iipet", ""},
	{"iipt", ""},
	{"iipe", ""},
	{"2peter", ""},
	{"2pet", ""},
	{"2pe", ""},
	{"2pt", ""},
	{"2p", ""},
	{"2ndpeter", ""},
	{"secondpeter", ""},

	{"1john", ""},
	{"1john", ""},
	{"1jhn", ""},
	{"1jn", ""},
	{"1j", ""},
	{"1john", ""},
	{"1jhn", ""},
	{"1joh", ""},
	{"1jn", ""},
	{"1jo", ""},
	{"1j", ""},
	{"ijohn", ""},
	{"ijhn", ""},
	{"ijoh", ""},
	{"ijn", ""},
	{"ijo", ""},
	{"1stjohn", ""},
	{"firstjohn", ""},

	{"2john", ""},
	{"2john", ""},
	{"2jhn", ""},
	{"2jn", ""},
	{"2j", ""},
	{"2john", ""},
	{"2jhn", ""},
	{"2joh", ""},
	{"2jn", ""},
	{"2jo", ""},
	{"2j", ""},
	{"iijohn", ""},
	{"iijhn", ""},
	{"iijoh", ""},
	{"iijn", ""},
	{"iijo", ""},
	{"2ndjohn", ""},
	{"secondjohn", ""},

	{"3john", ""},
	{"3john", ""},
	{"3jhn", ""},
	{"3jn", ""},
	{"3j", ""},
	{"3john", ""},
	{"3jhn", ""},
	{"3joh", ""},
	{"3jn", ""},
	{"3jo", ""},
	{"3j", ""},
	{"iiijohn", ""},
	{"iiijhn", ""},
	{"iiijoh", ""},
	{"iiijn", ""},
	{"iiijo", ""},
	{"3rdjohn", ""},
	{"thirdjohn", ""},

	{"jude", ""},
	{"jude", ""},
	{"jud", ""},
	{"jd", ""},

	{"revelation", ""},
	{"rev", ""},
	{"re", ""},
	{"therevelation", ""},
}
